### ISSUE TITLE
Better distinction for private/direct toots

### ISSUE THREAD

**Issue by davidbgk** [nileane/TangerineUI-for-Mastodon#67]
This is what I added to my custom CSS but I guess it can be better(!):

```css
.theme-default .status__wrapper-private {
  background: var(--color-accent-bg);
}
.theme-default .status__wrapper-direct {
  background: var(--color-accent);
}
```

The overall goal is made these particular (semi-)private toot stand up and avoid sharing them.

Before:

<img width="663" alt="Capture d’écran, le 2023-10-23 à 14 28 43" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/3556/f0d0a2f2-720f-45d0-8460-a6723a123811">

After (private):
<img width="658" alt="Capture d’écran, le 2023-10-23 à 14 29 31" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/3556/d442a494-e025-44fa-a518-b454859f10c7">

After (direct):
<img width="667" alt="Capture d’écran, le 2023-10-23 à 14 30 27" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/3556/3a376be8-52d1-4704-9543-d4feee27524d">
